name: "Release by Tag"

on:
  push:
    tags:
      - "v**"
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - id: vars
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\///' | sed -e 's/refs\/heads\///')
          cho "version=${VERSION}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: natsuneko-laboratory/create-unitypackage@v3.1.0
        with:
          files-glob: |
            Assets/NatsunekoLaboratory/ConstraintByHumanoid/**/*.*
          dest: dist/ConstraintByHumanoid-${{ needs.setup.outputs.version }}.unitypackage

      - uses: actions/upload-artifact@v2
        with:
          name: ConstraintByHumanoid
          path: dist/
